name: "Pre Release"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight UTC
  workflow_dispatch:

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build"
        run: |
          make

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GRAHAM_ESSAYS }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Paul Graham Essays"
          files: |
            *.epub
            *.pdf
            *.csv
