---
name: "pre-release"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"


jobs:
  pre-release:
    name: "EPUB & MOBI"
    runs-on: "macos-latest"

    steps:
      - name: Echo current date
        run: echo $NOW
      - name: "Build & test"
        run: |
          make dependencies
          make all

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GRAHAM_ESSAYS }}"
          automatic_release_tag: "latest"
          prerelease: true
          tag: ${{ github.event.repository.updated_at }}
          title: "Paul Graham Essays"
          files: |
            *.epub
            *.mobi
