name: "EPUB & PDF files"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    name: "EPUB & PDF"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: make all

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GRAHAM_ESSAYS }}"
        title: "Paul Graham Essays"
        files: |
          *.epub
          *.pdf
          *.csv