---
name: "pre-release"

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: "0 0 * * *"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "macos-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          make dependencies
          make all

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GRAHAM_ESSAYS }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Build files"
          files: |
            *.epub
            *.mobi
