name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install python@3.9
      
      - name: 🐍 Creating a safe place for a Python...
        run: |
          mkdir essays
          python3.9 -m venv .venv
          python3.9 -m pip install --upgrade pip
          source .venv/bin/activate
          pip install -r requirements.txt
          make fetch 
