name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing pandoc and calibre
      run: |
        sudo apt install pandoc -y
        sudo apt install calibre -y
    - name: Running app
      run: |
        make all
